site_name: Boko Hacks
site_url: https://bokohacks.com
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
nav:
  - Home: index.md
  - About : about.md
  - Event Archive: archive.md
  - Sponsors: thankyou.md
  
extra_css:
  - stylesheets/extra.css